@url = http://localhost:5000/users-module
@email = user1@confab.io
@password = secret
@role = user
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0NDlhMWZlOS1lODJkLTQ4MDItOGRiNS1iNTU1YWQ4NWY5OTMiLCJ1bmlxdWVfbmFtZSI6IjQ0OWExZmU5LWU4MmQtNDgwMi04ZGI1LWI1NTVhZDg1Zjk5MyIsImp0aSI6ImQwMDIzNzNiLWMyYTktNDBmZC1hM2ZhLTg5MjdjZTkyOGEzNSIsImlhdCI6IjE2NjE1MDY4MTQ1MzIiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJ1c2VyIiwicGVybWlzc2lvbnMiOlsiY29uZmVyZW5jZXMiLCJzcGVha2VycyIsInRpY2tldHMiLCJ1c2VycyJdLCJuYmYiOjE2NjE1MDY4MTQsImV4cCI6MTY2MTU0MjgxNCwiaXNzIjoiY29uZmFiIn0.Jyf8BSiISl14JmYuDJmuKyaYWaWPr-fwv_5CWiQeL38
###
GET {{url}}

###
GET {{url}}/account
Authorization: Bearer {{accessToken}}

###
POST {{url}}/account/sign-up
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}",
  "role": "{{role}}",
  "claims": {
    "permissions": ["conferences", "speakers", "tickets", "users"]
  }
}

###
POST {{url}}/account/sign-in
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}