@url = http://localhost:5000/users-module
@email = user1@confab.io
@password = secret
@role = user
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkNzNjYmM4Ny01Y2ExLTQ1ZDctYTQ5Yi1mNzQyNDNiM2Y4MDkiLCJ1bmlxdWVfbmFtZSI6ImQ3M2NiYzg3LTVjYTEtNDVkNy1hNDliLWY3NDI0M2IzZjgwOSIsImp0aSI6IjkzZDViYTI2LTVkZmMtNDUzYS05YWRkLTA1OTZjNjAwNmYzMyIsImlhdCI6IjE2NjE3Njc1NTE0MDciLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJ1c2VyIiwicGVybWlzc2lvbnMiOlsiY29uZmVyZW5jZXMiLCJzcGVha2VycyIsInRpY2tldHMiLCJ1c2VycyJdLCJuYmYiOjE2NjE3Njc1NTEsImV4cCI6MTY2MTgwMzU1MSwiaXNzIjoiY29uZmFiIn0.yQ2puyt5YGzPnmnwX5eNOYbh0JY6CFch7wfVxIqCT4o
###
GET {{url}}

###
GET {{url}}/account
Authorization: Bearer {{accessToken}}

###
POST {{url}}/account/sign-up
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}",
  "role": "{{role}}",
  "claims": {
    "permissions": ["conferences", "speakers", "tickets", "users", "hosts"]
  }
}

###
POST {{url}}/account/sign-in
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}