@url = http://localhost:5000/users-module
@email = user1@confab.io
@password = secret
@role = user
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ZjM1NjczNC0wOGMxLTQ0YTAtYmFkNi03MWI1N2I3MjFhMGMiLCJ1bmlxdWVfbmFtZSI6IjZmMzU2NzM0LTA4YzEtNDRhMC1iYWQ2LTcxYjU3YjcyMWEwYyIsImp0aSI6IjdkZTFkN2I2LTJjN2EtNDhiZi04ZTA3LTFhNzkzODQxODQ5MCIsImlhdCI6IjE2NjEyNTAyMDgzOTMiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJ1c2VyIiwicGVybWlzc2lvbnMiOlsiY29uZmVyZW5jZXMiLCJob3N0cyIsInNwZWFrZXJzIiwidGlja2V0cyIsInVzZXJzIl0sIm5iZiI6MTY2MTI1MDIwOCwiZXhwIjoxNjYxMjg2MjA4LCJpc3MiOiJjb25mYWIifQ.0t5Vnrwfn2NCi4owLDKAqQT65JZedoAsHF_cK69gTMo
###
GET {{url}}

###
GET {{url}}/account
Authorization: Bearer {{accessToken}}

###
POST {{url}}/account/sign-up
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}",
  "role": "{{role}}",
  "claims": {
    "permissions": ["conferences", "speakers", "tickets", "users"]
  }
}

###
POST {{url}}/account/sign-in
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}