@url = http://localhost:5000/conferences-module
@hostId = c055488e-3ae9-4925-81ad-d1e9e29e667b
@conferenceId = 85381adb-0528-4cff-b939-e4cf3ca954b1

###
GET {{url}}

###
POST {{url}}/hosts
Content-Type: application/json

{ 
    "name" : "Host #1",
    "description" : "Lorem Ipsum"
}

###
GET {{url}}/hosts/{{hostId}}

###
GET {{url}}/hosts

###
PUT {{url}}/hosts/{{hostId}}
Content-Type: application/json

{ 
    "name" : "Host #2",
    "description" : "Lorem Ipsum 321"
}

###
DELETE {{url}}/hosts/{{hostId}}

--------- CONFERENCES -----------

###
POST {{url}}/conferences
Content-Type: application/json

{ 
    "hostId" : "{{hostId}}",
    "name" : "Conference #6",
    "description" : "Lorem Ipsum",
    "location" : "Test 123",
    "from" : "2022-12-01",
    "to" : "2022-12-03",
    "participantsLimit" : "100",
    "logoUrl" : null 
}

###
GET {{url}}/conferences/{{conferenceId}}

###
GET {{url}}/conferences

###
PUT {{url}}/conferences/{{conferenceId}}
Content-Type: application/json

{ 
    "name" : "Conference #3",
    "description" : "Lorem Ipsum 321",
    "location" : "Warsaw"
}

###
DELETE {{url}}/conferences/{{conferenceId}}