@url = http://localhost:5000/conferences-module
@hostId = c055488e-3ae9-4925-81ad-d1e9e29e667b
@conferenceId = 85381adb-0528-4cff-b939-e4cf3ca954b1
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0NDlhMWZlOS1lODJkLTQ4MDItOGRiNS1iNTU1YWQ4NWY5OTMiLCJ1bmlxdWVfbmFtZSI6IjQ0OWExZmU5LWU4MmQtNDgwMi04ZGI1LWI1NTVhZDg1Zjk5MyIsImp0aSI6IjFkYTg3MWZmLTA5YTYtNDczZC1hZDU2LWE0OTJkODdlMzlmMSIsImlhdCI6IjE2NjE3Njc0NDAyOTciLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJ1c2VyIiwicGVybWlzc2lvbnMiOlsiY29uZmVyZW5jZXMiLCJzcGVha2VycyIsInRpY2tldHMiLCJ1c2VycyJdLCJuYmYiOjE2NjE3Njc0NDAsImV4cCI6MTY2MTgwMzQ0MCwiaXNzIjoiY29uZmFiIn0.a_5Z_cazeDXDKDAzItIDaaP6OUXNYZTnaptZnlrokxE

###
GET {{url}}

###
POST {{url}}/hosts
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{ 
    "name" : "Host #111",
    "description" : "Lorem Ipsum"
}

###
GET {{url}}/hosts/{{hostId}}

###
GET {{url}}/hosts

###
PUT {{url}}/hosts/{{hostId}}
Content-Type: application/json

{ 
    "name" : "Host #2",
    "description" : "Lorem Ipsum 321"
}

###
DELETE {{url}}/hosts/{{hostId}}

--------- CONFERENCES -----------

###
POST {{url}}/conferences
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{ 
    "hostId" : "{{hostId}}",
    "name" : "Conference #6",
    "description" : "Lorem Ipsum",
    "location" : "Test 123",
    "from" : "2022-12-01",
    "to" : "2022-12-03",
    "participantsLimit" : "100",
    "logoUrl" : null 
}

###
GET {{url}}/conferences/{{conferenceId}}

###
GET {{url}}/conferences

###
PUT {{url}}/conferences/{{conferenceId}}
Content-Type: application/json

{ 
    "name" : "Conference #3",
    "description" : "Lorem Ipsum 321",
    "location" : "Warsaw"
}

###
DELETE {{url}}/conferences/{{conferenceId}}