@url = http://localhost:5000/conferences-module
@hostId = c055488e-3ae9-4925-81ad-d1e9e29e667b
@conferenceId = 85381adb-0528-4cff-b939-e4cf3ca954b1
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ZjM1NjczNC0wOGMxLTQ0YTAtYmFkNi03MWI1N2I3MjFhMGMiLCJ1bmlxdWVfbmFtZSI6IjZmMzU2NzM0LTA4YzEtNDRhMC1iYWQ2LTcxYjU3YjcyMWEwYyIsImp0aSI6IjYyZjdjMzMyLTU2YjUtNDliNS04MmUyLTkxYjI4YzJiYTc5MSIsImlhdCI6IjE2NjEyNTE5NTU0NTIiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJ1c2VyIiwicGVybWlzc2lvbnMiOlsiY29uZmVyZW5jZXMiLCJob3N0cyIsInNwZWFrZXJzIiwidGlja2V0cyIsInVzZXJzIl0sIm5iZiI6MTY2MTI1MTk1NSwiZXhwIjoxNjYxMjg3OTU1LCJpc3MiOiJjb25mYWIifQ.l428P4XgGA9wKVtAKjX2mqrXhNyOnjYVNVyuwlQEhkg


###
GET {{url}}

###
POST {{url}}/hosts
Content-Type: application/json

{ 
    "name" : "Host #11",
    "description" : "Lorem Ipsum"
}

###
GET {{url}}/hosts/{{hostId}}

###
GET {{url}}/hosts

###
PUT {{url}}/hosts/{{hostId}}
Content-Type: application/json

{ 
    "name" : "Host #2",
    "description" : "Lorem Ipsum 321"
}

###
DELETE {{url}}/hosts/{{hostId}}

--------- CONFERENCES -----------

###
POST {{url}}/conferences
Content-Type: application/json

{ 
    "hostId" : "{{hostId}}",
    "name" : "Conference #6",
    "description" : "Lorem Ipsum",
    "location" : "Test 123",
    "from" : "2022-12-01",
    "to" : "2022-12-03",
    "participantsLimit" : "100",
    "logoUrl" : null 
}

###
GET {{url}}/conferences/{{conferenceId}}

###
GET {{url}}/conferences

###
PUT {{url}}/conferences/{{conferenceId}}
Content-Type: application/json

{ 
    "name" : "Conference #3",
    "description" : "Lorem Ipsum 321",
    "location" : "Warsaw"
}

###
DELETE {{url}}/conferences/{{conferenceId}}