@url = http://localhost:5000/speakers-module
@speakerId = 83d830fa-2e9d-4360-8a8a-12ff8e7381e9


###
GET {{url}}

###
POST {{url}}/speakers
Content-Type: application/json

{ 
    "email" : "test@test.pl",
    "fullName" : "Mieczysw Kopytko kolanko",
    "bio" : "Ho ho ho",
    "avatarUrl" : null
}

###
GET {{url}}/speakers/{{speakerId}}

###
GET {{url}}/speakers

###
PUT {{url}}/speakers/{{speakerId}}
Content-Type: application/json

{ 
    "fullName" : "Marek Citko",
    "bio" : "Hi hi hi",
    "email" : "testowo@testowo.pl"
}

###
DELETE {{url}}/speakers/{{speakerId}}